;; To select ELF output format, use format ELF directive. The default code setting for this format
;; is 32-bit. To create ELF file for the x86-64 architecture, use format ELF64 directive, in such
;; case the long mode code is generated by default.
;;
;; To create executable file, follow the format choice directive with the executable or dynamic
;; keyword and optionally the number specifying the brand of the target operating system (for
;; example value 3 would mark the executable for Linux system).
;; With this format selected it is allowed to use entry directive followed by the value to set as
;; entry point of program. On the other hand it makes extrn and public directives unavailable, and
;; instead of section it expects the segment directive followed by one or more segment permission
;; flags and optionally a marker of special ELF executable segment, which can be interpreter,
;; dynamic, note, gnuehframe, gnustack or gnurelro. Available permission flags are: readable,
;; writeable and executable. The origin of a non-special segment is aligned to page (4096 bytes).
format ELF64 executable 3

;; entry directive sets the entry point for Portable Executable, the value of entry point should
;; follow.
entry main

;; segment directive defines a new segment, it should be followed by label, which value will be the
;; number of defined segment, optionally use16 or use32 word can follow to specify whether code in
;; this segment should be 16-bit or 32-bit. The origin of segment is aligned to paragraph (16 bytes).
;; All the labels defined then will have values relative to the beginning of this segment.
segment executable

  main:
    ;; set exit code to 0.
    mov rax, 60
    mov rdi, 0
    syscall

    ;; ret, retn and retf instructions terminate the execution of a procedure and transfers control
    ;; back to the program that originally invoked the procedure using the address that was stored
    ;; on the stack by the call instruction.
    ;; ret is the equivalent for retn, which returns from the procedure that was executed using the
    ;; near call, while retf returns from the procedure that was executed using the far call.
    ret
